meta:
  engine: 4.1.0
units:
  cx: 17.5
  cy: 16.5
  mg: 50
points:
  mirror:
    ref: matrix_inner_top
    distance: mg
  zones:
    matrix:
      anchor.shift: [50,-100] # Fix KiCad placement
      columns:
        pinky:
          key:
            spread: 12
            splay: 0
            origin: [0, -10]
            width: cx
            height: cy
          rows:
            bottom:
              bind: [0, 30, 7, 0]
              column_net: C1
              row_net: R2
              mirror.column_net: C12
              mirror.row_net: R6
            home:
              bind: [0, 0, 0, 0]
              column_net: C1
              row_net: R3
              mirror.column_net: C12
              mirror.row_net: R5
            top:
              bind: [7, 15, 20, 0]
              column_net: C1
              row_net: R1
              mirror.column_net: C12
              mirror.row_net: R9
        ring:
          key:
            spread: cx - 1
            stagger: cy * 0.5
            splay: -10
            origin: [0, -16]
            width: cx
            height: cy
          rows:
            bottom:
              bind: [0, 0, 0, 0]
              column_net: C2
              row_net: R5
              mirror.column_net: C11
              mirror.row_net: R8
            home:
              bind: [0, 0, 0, 0]
              column_net: C2
              row_net: R4
              mirror.column_net: C11
              mirror.row_net: R4
            top:
              bind: [0, 10, 20, 0]
              column_net: C2
              row_net: R1
              mirror.column_net: C11
              mirror.row_net: R7
        middle:
          key:
            shift: [0, 0]
            spread: cx 
            stagger: cy/3
            splay: -8
            origin: [0, -12]
            width: cx
            height: cy
          rows:
            bottom:
              bind: [0, 0, 0, 0]
              column_net: C3
              row_net: R6
              mirror.column_net: C10
              mirror.row_net: R3
            home:
              bind: [0, 0, 0, 0]
              column_net: C3
              row_net: R7
              mirror.column_net: C10
              mirror.row_net: R9
            top:
              bind: [0, 0, 0, 0]
              column_net: C3
              row_net: R1
              mirror.column_net: C10
              mirror.row_net: R7
        index:
          key:
            spread: cx - .6
            stagger: -cy/2
            splay: -4
            origin: [0, -cx]
            width: cx
            height: cy
          rows:
            bottom:
              bind: [0, 0, 0, 0]
              column_net: C4
              row_net: R8
              mirror.column_net: C9
              mirror.row_net: R5
            home:
              bind: [0, 0, 0, 0]
              column_net: C4
              row_net: R9
              mirror.column_net: C9
              mirror.row_net: R8
            top:
              bind: [0, 0, 10, 10]
              column_net: C4
              row_net: R1
              mirror.column_net: C9
              mirror.row_net: R3
        inner:
          key:
            spread: cx+.5
            stagger: -cy/4
            splay: 0
            origin: [0, -cy]
            width: cx
            height: cy
          rows: 
            bottom:
              bind: [0, 0, 0, 0]
              column_net: C5
              row_net: R2
              mirror.column_net: C8
              mirror.row_net: R6
            home:
              bind: [0, 0, 0, 0]
              column_net: C5
              row_net: R4
              mirror.column_net: C8
              mirror.row_net: R3
            top:
              bind: [0, 40, 40, 0]
              column_net: C5
              row_net: R9
              mirror.column_net: C8
              mirror.row_net: R4
      rows:
        bottom:
          padding: cy + .5
        home:
          padding: cy + .5
        top:
    thumb:
      anchor:
        ref: matrix_inner_bottom
        shift: [-cx * 1.5 - 1,-cy-1]
      columns:
        first:
          key:
            splay: 0
            width: cx
            height: cy
          rows:
            only:
              column_net: C6
              row_net: R2
              mirror.column_net: C7
              mirror.row_net: R8
              bind: [15, 5, 0, 0]
        second:
          key:
            spread: cx + .75
            splay: -15
            origin: [-cx/2, -cx/2]
            width: cx
            height: cy
          rows:
            only:
              column_net: C6
              row_net: R7
              mirror.column_net: C7
              mirror.row_net: R6
              bind: [10, 5, 0, 5]
        third:
          key:
            spread: cx + .75
            splay: -15
            origin: [-cx/2, -cx/2]
            width: cx
            height: cy
          rows:
            only:
              column_net: C6
              row_net: R5
              mirror.column_net: C7
              mirror.row_net: R2
              bind: [15, 0, 0, 0]
outlines:
  raw:
    - what: rectangle
      where: true
      bound: true
      asym: both
      size: [cx, cy]
      corner: 0
  pcb:
    - what: outline
      name: raw
    - what: rectangle #center top horizontal (screw, controller pins, not USB area), mirrored
      where: matrix_pinky_top
      asym: both
      # width and horizontal shift fine-tuned for right edge (USB cut-out),
      # left edge is internal so not important.
      # height and vertical offest fine-tuned for top to match automatic top-left cut
      # (cover all the pins but still fit original case), bottom is internal so not important.
      size: [100, 30]
      adjust:
        shift: [49.5, 0.25]
      operation: add
    - what: rectangle #center bottom horizontal (inc. screw) and (at top) bottom of USB cut-out
      where: matrix_inner_top
      asym: source
      # width and horizontal shift set left & right edges, both both interal so some leaway.
      # height and vertical shift fine-tuned for top to be bottom of USB cut-out,
      # AND the bottom edge to match original & case.
      size: [70, 94]
      adjust:
        shift: [mg / 2, -23.3]
        orient: 22
      operation: add

  out-pcb:
    - what: outline
      name: pcb
      expand: 1
      joints: 1
      fillet: 0

  pretty-pcb-nf: # for drawing case.
    - what: outline
      name: pcb
      expand: 1
      joints: 1

  pretty-pcb: # final kicad edgecuts.
    - what: outline
      name: pretty-pcb-nf
      fillet: 0.5
    - what: rectangle # battery cut-out, eg 3.7v 110mAh 301230
      where: matrix_inner_top
      asym: source
      size: [35,15]  # for 12x30mm battery
      adjust:
        shift: [(mg / 2), -35]
        orient: 22
      operation: subtract

  ## plate utils.
  plate-cutout:
    - what: rectangle
      where: true
      size: [13.8, 13.8]
  plate-notch:
    - what: rectangle
      where: true
      size: [16, 16]
pcbs:
  gamma-omega-hesse:
    template: kicad8
    outlines:
      edge:
        outline: pretty-pcb
    footprints:
      choc_hotswap:
        what: ceoloide/switch_choc_v1_v2
        where: true
        params:
          from: "{{column_net}}"
          to: "{{row_net}}"
          side: B
          include_corner_marks: true
          include_keycap: true
          keycap_height: cy
          keycap_width: cx
          reversible: false
          solder: true
          hotswap: true
          # Workaround for footprint oddity (logged as issue 64)
          # to get v2 centre hole, but no stabilizers etc added:
          choc_v2_support: true
          include_stabilizer_pad: false
          center_hole_diameter: 5.0
          outer_pad_width_front: 2.0
          outer_pad_width_back: 2.0
          keycap_3dmodel_filename: '${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Keycap_MBK_Black_1u.step'
          keycap_3dmodel_xyz_rotation: [180, 0, 0]
          keycap_3dmodel_xyz_offset: [0, 0, -8]
          switch_3dmodel_filename: '${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Switch.step'
          switch_3dmodel_xyz_rotation: [180, 0, 0]
          switch_3dmodel_xyz_offset: [0, 0, -1.6]
          hotswap_3dmodel_filename: '${EG_INFUSED_KIM_3D_MODELS}/Choc_V1_Hotswap.step'
          hotswap_3dmodel_xyz_rotation: [180, 0, 0]
          hotswap_3dmodel_xyz_offset: [0, 0, -1.6]
      mcu:
        what: ceoloide/mcu_supermini_nrf52840
        where:
          ref: matrix_inner_top
        adjust:
          # The Supermini NRF52840 is reportedly 17.78mm wide, 33.00mm long
          # (and 30.48mm between the center of the top and bottom pins).
          # The original Raspberry Pi Pico is also 17.78mm wide, but 51mm long
          # (and 48.26mm between the center of the top and bottom pins).
          # This is 51 - 33 = 18mm shorter, so adjust the original y-offset by
          # half of that - so the center is 9mm higher up:
          shift: [mg / 2, 15.67] 
          orient: 22
        params:
          reversible: false
          include_extra_pins: true
          # Top left as look at chips, going down
          P1: C3
          P0: R1
          P2: C4
          P3: C5
          P4: R4
          P5: R3
          P6: R8
          P7: C2
          P8: C1
          P9: C6
          # Bottom right, going up
          P10: R2
          P16: R5
          P14: R6
          P15: C8
          P18: C9
          P19: C10
          P20: R9
          P21: R7
          # Extra trio in middle
          P101: C11
          P102: C12
          P107: C7
      case-hole-lt:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_pinky_top
          shift: [-7, 13.75]
      case-hole-lt-mirror:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_pinky_top
          shift: [-7, 13.75]
      case-hole-lb:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_pinky_bottom
          shift: [-7, -13.75]
      case-hole-lb-mirror:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_pinky_bottom
          shift: [-7, -13.75]
      case-hole-rt:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_pinky_top
          shift: [82, 11.75]
      case-hole-rt-mirror:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_pinky_top
          shift: [82, 11.75]
      case-hole-rb:
        what: ceoloide/mounting_hole_plated
        where:
          ref: matrix_pinky_bottom
          shift: [88, -51]
      case-hole-rb-mirror:
        what: ceoloide/mounting_hole_plated
        where:
          ref: mirror_matrix_pinky_bottom
          shift: [88, -51]
